// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/home/navbar";
import { Footer } from "@/components/home/footer";
import Lenis from "lenis";
import SmoothScroll from "@/components/home/SmoothScroll";
import { ClerkProvider } from "@clerk/nextjs";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <TooltipProvider>
              {/* <AppSidebar /> */}
              {/* <div className="relative flex justify-center items-center min-h-screen flex-col"> */}
              {/* <SmoothScroll> */}

              <ClerkProvider>
                {" "}
                <div className="w-full flex flex-col">
                  <Navbar />
                  {children}
                </div>
              </ClerkProvider>
              {/* <Footer /> */}
              {/* </SmoothScroll> */}
              {/* </div> */}
              <Toaster />
            </TooltipProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
